### ISSUE TITLE
Error while trying to run the project

### ISSUE THREAD

**Issue by anoop-tm** [AnnaPS/infogames#1]
```
Launching lib/main.dart on Android SDK built for x86 in debug mode...
lib/main.dart:1
Error detected in pubspec.yaml:
No file or variants found for asset: assets/.env.



FAILURE: Build failed with an exception.
```

**Comment by AnnaPS** [comment]
Hi @anoop-tm , thanks for opening the issue.

This error occurs because you need to create your own **.env** file. 
There you need to add your API_KEY from RAWG API. 

On the readme file, I added some instructions to add **.env** file and its content. 
-  [Readme](https://github.com/AnnaPS/infogames#readme)

Hope that it helps!

**Comment by salkhan-ops** [comment]
thank you for the nice tutorial. Very informative. 

There is an error, i can't figure out i.e., repositories/game.dart, line filters: Filters(years: [ ]), causing 'Const variables must be initialized with a constant value'.
